### ISSUE TITLE
SeLoadDriver

### ISSUE THREAD

**Issue by vletoux** [gtworek/Priv2Admin#1]
You’re missing several privileges escalation such as SeLoadDriver
Get a look at Andreas work
(Decoder.ap)

**Comment by gtworek** [comment]
I have left it for later. It is quite huge topic and I preferred to focus on other privileges.
Thank you a lot, for sure it will help me and I will cover it at least briefly soon.
"?" means "I had no time yet" ;))

Greg

--
G.
________________________________
